import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#00f5ff',
  primaryDark: '#0066ff',
  background: '#0a0a0a',
  backgroundDark: '#1a1a2e',
  backgroundLight: '#16213e',
  screenBg: '#0f0f1e',
  white: '#fff',
  black: '#000',
};

export const gradients = {
  primary: ['#00f5ff', '#0066ff'] as const,
  background: ['#0a0a0a', '#1a1a2e'] as const,
  screen: ['#0f0f1e', '#1a1a2e'] as const,
  phone: ['#1a1a2e', '#16213e'] as const,
  card: ['rgba(26, 26, 46, 0.8)', 'rgba(22, 33, 62, 0.8)'] as const,
  cardLight: ['rgba(26, 26, 46, 0.6)', 'rgba(22, 33, 62, 0.6)'] as const,
};

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.screenBg,
    padding: 20,
  },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statusBarText: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: '500',
  },
  screenTitle: {
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 18,
    letterSpacing: 1,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 245, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.3)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginBottom: 15,
  },
  aiBadgeText: {
    fontSize: 10,
    color: colors.primary,
  },
  aiPulse: {
    width: 8,
    height: 8,
    backgroundColor: colors.primary,
    borderRadius: 4,
  },
  button: {
    backgroundColor: colors.primary,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 8,
  },
  buttonText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  buttonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  buttonSecondaryText: {
    color: colors.primary,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 15,
  },
  statBox: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: 'rgba(26, 26, 46, 0.8)',
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primary,
  },
  statLabel: {
    fontSize: 10,
    color: 'rgba(0, 245, 255, 0.7)',
    marginTop: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  hazardCard: {
    backgroundColor: 'rgba(26, 26, 46, 0.8)',
    padding: 14,
    borderRadius: 10,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  hazardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 5,
  },
  hazardDistance: {
    fontSize: 12,
    color: colors.primary,
    opacity: 0.8,
  },
  confidenceMeter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  confidenceMeterText: {
    fontSize: 10,
    color: colors.primary,
  },
  confidenceBar: {
    flex: 1,
    height: 3,
    backgroundColor: 'rgba(0, 245, 255, 0.2)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  confidenceFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 2,
  },
  mapArea: {
    backgroundColor: 'rgba(26, 26, 46, 0.8)',
    height: 280,
    borderRadius: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
    position: 'relative',
  },
  mapGrid: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  mapMarker: {
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: colors.primary,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'rgba(0, 245, 255, 0.3)',
  },
  searchBox: {
    backgroundColor: 'rgba(26, 26, 46, 0.6)',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.3)',
    fontSize: 13,
    marginBottom: 15,
    color: colors.white,
  },
  cameraView: {
    backgroundColor: colors.black,
    height: 200,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0, 245, 255, 0.3)',
  },
  detectionBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0, 245, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.5)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  detectionBadgeText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '600',
  },
  listItem: {
    backgroundColor: 'rgba(26, 26, 46, 0.6)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  listItemText: {
    fontSize: 13,
    color: colors.white,
    fontWeight: '600',
  },
  listItemSubtext: {
    fontSize: 10,
    color: colors.primary,
  },
  settingsSection: {
    backgroundColor: 'rgba(26, 26, 46, 0.6)',
    padding: 14,
    borderRadius: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  settingsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 245, 255, 0.1)',
  },
  settingsItemLast: {
    borderBottomWidth: 0,
  },
  settingsText: {
    fontSize: 13,
    color: colors.white,
  },
  toggle: {
    width: 45,
    height: 24,
    backgroundColor: 'rgba(0, 245, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.3)',
    borderRadius: 12,
    justifyContent: 'center',
    padding: 2,
  },
  toggleActive: {
    backgroundColor: colors.primary,
  },
  toggleThumb: {
    width: 18,
    height: 18,
    backgroundColor: colors.white,
    borderRadius: 9,
  },
  modelCard: {
    backgroundColor: 'rgba(26, 26, 46, 0.8)',
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  modelName: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
  },
  modelStatus: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.7)',
  },
  severityContainer: {
    backgroundColor: 'rgba(26, 26, 46, 0.6)',
    padding: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  severityLabel: {
    fontSize: 11,
    color: colors.primary,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  sliderTrack: {
    height: 6,
    backgroundColor: 'rgba(0, 245, 255, 0.1)',
    borderRadius: 3,
    marginBottom: 8,
    position: 'relative',
  },
  sliderFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 3,
  },
  sliderThumb: {
    position: 'absolute',
    width: 16,
    height: 16,
    backgroundColor: colors.primary,
    borderRadius: 8,
    top: -5,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sliderLabelText: {
    fontSize: 10,
    color: 'rgba(0, 245, 255, 0.6)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
